name: GitHub Actions Spring Boot 4 Test

on: [workflow_dispatch]

jobs:
  view_login_page:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v6
        with:
          name: staging
          path: staging